//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DietHolder2WebApplication.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int productId { get; set; }
        public string productName { get; set; }
        public Nullable<decimal> productPrice { get; set; }
        public Nullable<double> productCarboValue { get; set; }
        public Nullable<double> productProteinValue { get; set; }
        public Nullable<double> productFatValue { get; set; }
    }
}
